var list_products =[
{
    "name":"iphone 5s",
    "company":"iphones",
    "img":"image/iphone-5s.jpg",
    "price":"890.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"LED-backlit IPS LCD",
        "os":"IOS 10",
        "camera":"1.2MP",
        "cameraFront":"8MP",
        "cpu":"Apple A7",
        "ram":"1 GB",
        "rom":"6 GB",
        "battery":"1560 mAh",
    },
    "masp":"iphone15"
},
{
    "name":"iphone 4",
    "company":"iphones",
    "img":"image/iphone-4.jpg",
    "price":"1.000.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"LED-backlit IPS LCD",
        "os":"IOS",
        "camera":"0.3MP",
        "cameraFront":"5MP",
        "cpu":"IMG PowerVR SGX535",
        "ram":"512 MB",
        "rom":"8 GB",
        "battery":"1420 mAh",
    },
    "masp":"iphone16"
},
{
    "name":"iphone 3gs",
    "company":"iphones",
    "img":"image/iphone-3GS.jpg",
    "price":"400.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"HVGA",
        "os":"ios",
        "camera":" ",
        "cameraFront":"3.2MP",
        "cpu":"IMG PowerVR SGX535",
        "ram":"512 MB",
        "rom":"8 GB",
        "battery":"1200 mAh",
    },
    "masp":"iphone17"
},
{
    "name":"iphone 6",
    "company":"iphones",
    "img":"image/iphone-6.jpg",
    "price":"3.490.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"LED-backlit IPS LCD",
        "os":"ios 12",
        "camera":"1.2MP",
        "cameraFront":"8MP",
        "cpu":"Apple A8",
        "ram":"1 GB",
        "rom":"16 GB",
        "battery":"1810 mAh",
    },
    "masp":"iphone18"
},
{
    "name":"iphone 6 plus",
    "company":"iphones",
    "img":"image/iphone-6-plus.jpg",
    "price":"4.290.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"LED-backlit IPS LCD",
        "os":"ios 12",
        "camera":"1.2MP",
        "cameraFront":"8MP",
        "cpu":"Apple A8",
        "ram":"1 GB",
        "rom":"16 GB",
        "battery":"2915 mAh",
    },
    "masp":"iphone19"
},
{
    "name":"iphone 6s",
    "company":"iphones",
    "img":"image/iphone-6s.jpg",
    "price":"1.650.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"LED-backlit IPS LCD",
        "os":"ios 11",
        "camera":"5MP",
        "cameraFront":"12MP",
        "cpu":"Apple A9",
        "ram":"2 GB",
        "rom":"16 GB",
        "battery":"1715 mAh",
    },
    "masp":"iphone20"
},
{
    "name":"samsung Galaxy A04s",
    "company":"samsung",
    "img":"image/Samsung-Galaxy-A04s.jpg",
    "price":"2.490.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"Super AMOLED",
        "os":"Android 13",
        "camera":"5MP",
        "cameraFront":"50MP-2MP-2MP",
        "cpu":"Exynos 850",
        "ram":"4 GB",
        "rom":"64 GB",
        "battery":"5000 mAh",
    },
    "masp":"samsung14"
},
{
    "name":"samsung Galaxy A54",
    "company":"samsung",
    "img":"image/Samsung-Galaxy-A54.jpg",
    "price":"9.590.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"Super AMOLED",
        "os":"Android 13",
        "camera":"32MP",
        "cameraFront":"50MP-12MP-5MP",
        "cpu":"Exynos 1380",
        "ram":"8 GB",
        "rom":"256 GB",
        "battery":"5000 mAh",
    },
    "masp":"samsung15"
},
{
    "name":"Samsung Galaxy S20 FE ",
    "company":"samsung",
    "img":"image/Samsung-Galaxy-S20-FE.jpg",
    "price":"7.200.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"Super AMOLED",
        "os":"Android 10",
        "camera":"32MP",
        "cameraFront":"12MP-8MP-12MP",
        "cpu":"Snapdragon 865",
        "ram":"8 GB",
        "rom":"256 GB",
        "battery":"4500 mAh",
    },
    "masp":"samsung16"
},
{
    "name":"Samsung Galaxy S20",
    "company":"samsung",
    "img":"image/Samsung-Galaxy-s20.jpg",
    "price":"6.990.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"Dynamic AMOLED 2X",
        "os":"Android 10",
        "camera":"32MP",
        "cameraFront":"12MP-8MP-12MP",
        "cpu":"Snapdragon 865",
        "ram":"8 GB",
        "rom":"256 GB",
        "battery":"4500 mAh",
    },
    "masp":"samsung17"
},
{
    "name":"Samsung Galaxy a32",
    "company":"samsung",
    "img":"image/samsung-galaxy-a32.jpg",
    "price":"6.490.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"Dynamic AMOLED 2X",
        "os":"Android 11",
        "camera":"20MP",
        "cameraFront":"64MP-8MP-5MP-5MP",
        "cpu":"MediaTek Helio G80",
        "ram":"6 GB",
        "rom":"128 GB",
        "battery":"5000 mAh",
    },
    "masp":"samsung18"
},
{
    "name":"Samsung Galaxy Z Flip3",
    "company":"samsung",
    "img":"image/samsung-galaxy-z-flip-3.jpg",
    "price":"14.990.000đ",
    "listprice":"10milion-15milion",
    "detail":{
        "screen":"Dynamic AMOLED 2X",
        "os":"Android 11",
        "camera":"10MP",
        "cameraFront":"12MP-12MP",
        "cpu":"Snapdragon 888",
        "ram":"8 GB",
        "rom":"256 GB",
        "battery":"3300 mAh",
    },
    "masp":"samsung19"
},
{
    "name":"OPPO A77s",
    "company":"oppo",
    "img":"image/oppo-a77s.jpg",
    "price":"5.090.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"IPS LCD",
        "os":"Android 12",
        "camera":"8MP",
        "cameraFront":"50MP-2MP",
        "cpu":"Snapdragon 680",
        "ram":"8 GB",
        "rom":"128 GB",
        "battery":"5000 mAh",
    },
    "masp":"oppo14"
},
{
    "name":"OPPO A55",
    "company":"oppo",
    "img":"image/OPPO-A55.jpg",
    "price":"3.490.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"IPS LCD",
        "os":"Android 11",
        "camera":"16MP",
        "cameraFront":"50MP-2MP-2MP",
        "cpu":"MediaTek Helio G35",
        "ram":"4 GB",
        "rom":"64 GB",
        "battery":"5000 mAh",
    },
    "masp":"oppo15"
},
{
    "name":"OPPO A78",
    "company":"oppo",
    "img":"image/oppo-a78.jpg",
    "price":"6.990.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"IPS LCD",
        "os":"Android 13",
        "camera":"8MP",
        "cameraFront":"50MP-2MP",
        "cpu":"Snapdragon 680",
        "ram":"8 GB",
        "rom":"256 GB",
        "battery":"5000 mAh",
    },
    "masp":"oppo16"
},
{
    "name":"OPPO A57",
    "company":"oppo",
    "img":"image/oppo-a57.jpg",
    "price":"3.790.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"IPS LCD",
        "os":"Android 12",
        "camera":"8MP",
        "cameraFront":"13MP-2MP",
        "cpu":"MediaTek Helio G35",
        "ram":"4 GB",
        "rom":"128 GB",
        "battery":"5000 mAh",
    },
    "masp":"oppo17"
},
{
    "name":"OPPO A17k",
    "company":"oppo",
    "img":"image/oppo-a17k.jpg",
    "price":"2.990.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"IPS LCD",
        "os":"Android 12",
        "camera":"5MP",
        "cameraFront":"8MP",
        "cpu":"MediaTek Helio G35",
        "ram":"3 GB",
        "rom":"64 GB",
        "battery":"5000 mAh",
    },
    "masp":"oppo18"
},
{
    "name":"OPPO A18",
    "company":"oppo",
    "img":"image/oppo-a18.jpg",
    "price":"3.990.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"IPS LCD",
        "os":"Android 13",
        "camera":"5MP",
        "cameraFront":"8MP-2MP",
        "cpu":"MediaTek Helio G85",
        "ram":"4 GB",
        "rom":"128 GB",
        "battery":"5000 mAh",
    },
    "masp":"oppo19"
},
{
    "name":"xiaomi poco x5",
    "company":"xiaomi",
    "img":"image/xiaomi-poco-x5.jpg",
    "price":"5.450.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"AMOLED",
        "os":"MIUI 14",
        "camera":"13MP",
        "cameraFront":"48MP-8MP-2MP",
        "cpu":"Snapdragon 695",
        "ram":"6 GB",
        "rom":"128 GB",
        "battery":"5000 mAh",
    },
    "masp":"xiaomi21"
},
{
    "name":"xiaomi poco x5 pro",
    "company":"xiaomi",
    "img":"image/poco-x5-pro.jpg",
    "price":"7.390.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"AMOLED",
        "os":"MIUI 14",
        "camera":"16MP",
        "cameraFront":"108MP-8MP-2MP",
        "cpu":"Snapdragon 778g",
        "ram":"8 GB",
        "rom":"256 GB",
        "battery":"5000 mAh",
    },
    "masp":"xiaomi22"
},
{
    "name":"xiaomi poco m5s",
    "company":"xiaomi",
    "img":"image/poco-m5s.jpg",
    "price":"4.290.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"AMOLED",
        "os":"MIUI 14",
        "camera":"13MP",
        "cameraFront":"64MP-8MP-2MP-2MP",
        "cpu":"Mediatek Helio G95",
        "ram":"6 GB",
        "rom":"128 GB",
        "battery":"5000 mAh",
    },
    "masp":"xiaomi23"
},
{
    "name":"xiaomi poco m5",
    "company":"xiaomi",
    "img":"image/poco-m5.jpg",
    "price":"4.400.000đ",
    "listprice":"0milion-5milion",
    "detail":{
        "screen":"IPS LCD",
        "os":"MIUI 14",
        "camera":"5MP",
        "cameraFront":"50MP-2MP-2MP",
        "cpu":"Mediatek Helio G99",
        "ram":"6 GB",
        "rom":"128 GB",
        "battery":"5000 mAh",
    },
    "masp":"xiaomi24"
},
{
    "name":"xiaomi poco f4",
    "company":"xiaomi",
    "img":"image/xiaomi-poco-f4.jpg",
    "price":"9.190.000đ",
    "listprice":"5milion-10milion",
    "detail":{
        "screen":"AMOLED",
        "os":"MIUI 14",
        "camera":"20MP",
        "cameraFront":"64MP-8MP-2MP",
        "cpu":"Qualcomm Snapdragon 870",
        "ram":"8 GB",
        "rom":"256 GB",
        "battery":"5000 mAh",
    },
    "masp":"xiaomi25"
},

]